/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Factura;

import Persistencia.PersistenciaProductos;
import Persistencia.PersistenciaSucursal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author andre
 */
public class jFrameFactura extends javax.swing.JFrame {

    /**
     * Creates new form jFrameFactura
     */
    public jFrameFactura() {
        initComponents();
        
        for (Producto producto : PersistenciaProductos.getArrayProductos()) {
            jCmbProductos.addItem(producto);
        }
        
        for (Sucursal sucursal : PersistenciaSucursal.getArraySucursales()) {
            jCmbSucursal.addItem(sucursal);
        }
        
        modeloTablas = (DefaultTableModel)jTblProductos.getModel();
    }
    
    private DefaultTableModel modeloTablas;
    private Factura factura;
    private String formatoDosDecimales = "%.2f";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTxtNFactura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jRbContado = new javax.swing.JRadioButton();
        jRbCredito = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jCmbSucursal = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTxtCantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCmbProductos = new javax.swing.JComboBox<>();
        jBtnAgregarProducto = new javax.swing.JButton();
        jBtnCrearFactura = new javax.swing.JButton();
        jBtnTerminarFactura = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblProductos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTxtSubTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtDescuento = new javax.swing.JTextField();
        jTxtImpuesto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Facturación");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("No.Factura");

        jTxtNFactura.setEditable(false);

        jLabel2.setText("Tipo de factura");

        buttonGroup1.add(jRbContado);
        jRbContado.setSelected(true);
        jRbContado.setText("Contado");
        jRbContado.setEnabled(false);

        buttonGroup1.add(jRbCredito);
        jRbCredito.setText("Crédito");
        jRbCredito.setEnabled(false);

        jLabel3.setText("Sucursal");

        jCmbSucursal.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Cantidad");

        jTxtCantidad.setEnabled(false);

        jLabel5.setText("Producto");

        jCmbProductos.setEnabled(false);

        jBtnAgregarProducto.setText("Agregar");
        jBtnAgregarProducto.setEnabled(false);
        jBtnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnAgregarProducto)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAgregarProducto))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jBtnCrearFactura.setText("Crear factura");
        jBtnCrearFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCrearFacturaActionPerformed(evt);
            }
        });

        jBtnTerminarFactura.setText("Terminar factura");
        jBtnTerminarFactura.setEnabled(false);
        jBtnTerminarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTerminarFacturaActionPerformed(evt);
            }
        });

        jTblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio", "Cantidad", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTblProductos);

        jLabel6.setText("Sub total");

        jTxtSubTotal.setEditable(false);
        jTxtSubTotal.setEnabled(false);

        jLabel7.setText("Descuento");

        jTxtDescuento.setEditable(false);
        jTxtDescuento.setEnabled(false);

        jTxtImpuesto.setEditable(false);
        jTxtImpuesto.setEnabled(false);

        jLabel8.setText("Impuesto");

        jLabel9.setText("Total");

        jTxtTotal.setEditable(false);
        jTxtTotal.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                            .addComponent(jCmbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(39, 39, 39)
                                            .addComponent(jTxtNFactura)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRbContado)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRbCredito)))
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtnTerminarFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnCrearFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNFactura)
                    .addComponent(jBtnCrearFactura))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jRbContado)
                            .addComponent(jRbCredito)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jBtnTerminarFactura)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCmbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jBtnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarProductoActionPerformed
        // TODO add your handling code here:
        LineaDetalle lineaDetalle = new LineaDetalle(Integer.parseInt(jTxtCantidad.getText()),
                (Producto)jCmbProductos.getSelectedItem());
        
        factura.agregarLineaDetalle(lineaDetalle);
        
        Object[] fila = new Object[4];
        
        fila[0] = lineaDetalle.getProducto().getNombre();
        fila[1] = lineaDetalle.getProducto().getPrecioBasico();
        fila[2] = lineaDetalle.getCantidad();
        fila[3] = lineaDetalle.costoLineaDetalle();
        modeloTablas.addRow(fila);

        jTxtSubTotal.setText(String.format(formatoDosDecimales, factura.calcularSubTotal()) + "₡");
        jTxtDescuento.setText(String.format(formatoDosDecimales, factura.descuento()) + "₡");
        jTxtImpuesto.setText(String.format(formatoDosDecimales, factura.calcularImpuesto()) + "₡");
        jTxtTotal.setText(String.format(formatoDosDecimales, factura.calcularTotalFactura()) + "₡");
    }//GEN-LAST:event_jBtnAgregarProductoActionPerformed

    private void jBtnCrearFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCrearFacturaActionPerformed
        // TODO add your handling code here:}
        TipoFactura tipoFactura;
        if (jRbContado.isSelected()) {
            tipoFactura = TipoFactura.CONTADO;
        }
        else{
            tipoFactura = TipoFactura.CREDITO;
        }
        factura = new Factura(tipoFactura);
        jTxtNFactura.setText(String.valueOf(factura.getNumeroFactura()));
        habilitar(true);
        jBtnCrearFactura.setEnabled(false);
        jBtnTerminarFactura.setEnabled(true);
    }//GEN-LAST:event_jBtnCrearFacturaActionPerformed

    private void jBtnTerminarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTerminarFacturaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, factura.display());
        jTxtCantidad.setText("");
        modeloTablas.setRowCount(0);
        jTxtSubTotal.setText("");
        jTxtDescuento.setText("");
        jTxtImpuesto.setText("");
        jTxtTotal.setText("");
        habilitar(false);
        jBtnCrearFactura.setEnabled(true);
        jBtnTerminarFactura.setEnabled(false);
        Sucursal sucursal = (Sucursal)jCmbSucursal.getSelectedItem();
        sucursal.agregarFactura(factura);
    }//GEN-LAST:event_jBtnTerminarFacturaActionPerformed

    private void habilitar(boolean verdaderoFalso){
        jTxtCantidad.setEnabled(verdaderoFalso);
        jBtnAgregarProducto.setEnabled(verdaderoFalso);
        jCmbSucursal.setEnabled(verdaderoFalso);
        jCmbProductos.setEnabled(verdaderoFalso);
        jRbContado.setEnabled(verdaderoFalso);
        jRbCredito.setEnabled(verdaderoFalso);
        jTxtSubTotal.setEnabled(verdaderoFalso);
        jTxtDescuento.setEnabled(verdaderoFalso);
        jTxtImpuesto.setEnabled(verdaderoFalso);
        jTxtTotal.setEnabled(verdaderoFalso);
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnAgregarProducto;
    private javax.swing.JButton jBtnCrearFactura;
    private javax.swing.JButton jBtnTerminarFactura;
    private javax.swing.JComboBox<Producto> jCmbProductos;
    private javax.swing.JComboBox<Sucursal> jCmbSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRbContado;
    private javax.swing.JRadioButton jRbCredito;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblProductos;
    private javax.swing.JTextField jTxtCantidad;
    private javax.swing.JTextField jTxtDescuento;
    private javax.swing.JTextField jTxtImpuesto;
    private javax.swing.JTextField jTxtNFactura;
    private javax.swing.JTextField jTxtSubTotal;
    private javax.swing.JTextField jTxtTotal;
    // End of variables declaration//GEN-END:variables
}
