/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Factura;

import Persistencia.PersistenciaSucursal;
import javax.swing.DefaultListModel;

/**
 *
 * @author andre
 */
public class jInternalFramefacturas extends javax.swing.JInternalFrame {

    /**
     * Creates new form jInternalFramefacturas
     */
    public jInternalFramefacturas() {
        initComponents();
        for (Sucursal sucursal : PersistenciaSucursal.getArraySucursales()) {
            jCmbSucursal.addItem(sucursal);
        }
    }
    
    DefaultListModel modelo = new DefaultListModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCmbSucursal = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jBtnBuscarFacturas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListFacturas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jBtnVerDetalles = new javax.swing.JButton();

        setClosable(true);
        setTitle("Consultas Facturas");

        jLabel1.setText("Sucursales");

        jBtnBuscarFacturas.setText("Buscar facturas");
        jBtnBuscarFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarFacturasActionPerformed(evt);
            }
        });

        jListFacturas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListFacturas);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jBtnVerDetalles.setText("Ver detalles");
        jBtnVerDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVerDetallesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jCmbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jBtnBuscarFacturas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnVerDetalles)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnBuscarFacturas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnVerDetalles))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBuscarFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarFacturasActionPerformed
        // TODO add your handling code here:
        modelo.clear();
        for (Factura factura : PersistenciaSucursal.getSucursal((Sucursal)jCmbSucursal.getSelectedItem()).getArrayFacturas()) {
            modelo.addElement(factura);
        }
        jListFacturas.setModel(modelo);
    }//GEN-LAST:event_jBtnBuscarFacturasActionPerformed

    private void jBtnVerDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVerDetallesActionPerformed
        // TODO add your handling code here:
        if(jListFacturas.getSelectedValue() != null){
            jTextArea1.setText(jListFacturas.getSelectedValue().display());
        }
    }//GEN-LAST:event_jBtnVerDetallesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscarFacturas;
    private javax.swing.JButton jBtnVerDetalles;
    private javax.swing.JComboBox<Sucursal> jCmbSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<Factura> jListFacturas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
